language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  
# command to run tests
script:
  - python -m pytest --cov=app tests/

after_success:
- coveralls